[package]
name = "osm_api"
version = "0.1.0"
authors = ["Lukáš Tyrychtr <lukastyrychtr@gmail.com>"]
edition = "2018"

[dependencies]
serde = {version="*", features=["derive"]}
serde_json = "*"
thiserror = "*"
ureq = {version="*", default_features=false, features=["tls"]}
rusqlite = {"version" = "*", "features" = ["bundled-windows"]}
sqlitemap = {path="../sqlitemap"}
log = "*"
itertools = "*"
lazy_static = "*"
chrono = "*"
xml-rs = "*"
tempfile = "*"
bincode = "*"
hashbrown = {version="*", features=["serde"]}
wkb = "*"
geo-types = "*"