[package]
name = "redis_api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
osm_db = {path = "../osm_db"}
redis = "1.0.2"
thiserror = "2.0.18"
log = "0.4.29"
